module.exports = {
  anvil: { isolation: 'global', compatibility: ['inventory', 'experience', 'blocks:anvil'] },
  bed: { isolation: 'global', compatibility: ['time', 'blocks:bed'] },
  book: { isolation: 'global', compatibility: ['inventory'] },
  bossBar: { isolation: 'global', compatibility: ['bossbar'] },
  breath: { isolation: 'global', compatibility: ['player-state'] },
  chat: { isolation: 'global', compatibility: ['chat'] },
  commandBlock: { isolation: 'global', compatibility: ['blocks:command_block', 'chat'] },
  complete: { isolation: 'global', compatibility: [] },
  consume: { isolation: 'global', compatibility: ['effects', 'inventory'] },
  crafting: { isolation: 'global', compatibility: ['inventory', 'blocks:crafting'] },
  creative: { isolation: 'global', compatibility: ['inventory', 'gamemode'] },
  digAndBuild: { isolation: 'workspace', compatibility: [], workspaceRadius: 8 },
  digEverything: { isolation: 'global', compatibility: ['inventory', 'blocks:dig'] },
  dimensionName: { isolation: 'global', compatibility: [] },
  displayName: { isolation: 'global', compatibility: [] },
  elytra: { isolation: 'global', compatibility: ['inventory', 'player-state'] },
  enchanting: { isolation: 'global', compatibility: ['inventory', 'experience', 'blocks:enchanting'] },
  exampleBee: { isolation: 'workspace', compatibility: [], workspaceRadius: 12, exampleBot: true },
  exampleBlockFinder: { isolation: 'global', compatibility: ['chat', 'example-bot'] },
  exampleDigger: { isolation: 'workspace', compatibility: [], workspaceRadius: 12, exampleBot: true },
  exampleInventory: { isolation: 'workspace', compatibility: [], workspaceRadius: 12, exampleBot: true },
  experience: { isolation: 'global', compatibility: ['experience'] },
  fishing: { isolation: 'global', compatibility: ['blocks:water', 'inventory'] },
  furnace: { isolation: 'global', compatibility: ['inventory', 'blocks:furnace'] },
  gamemode: { isolation: 'global', compatibility: ['gamemode'] },
  heldItem: { isolation: 'global', compatibility: ['inventory'] },
  nether: { isolation: 'global', compatibility: ['dimension', 'portal'] },
  particles: { isolation: 'global', compatibility: ['particles'] },
  placeEntity: { isolation: 'global', compatibility: ['entities', 'inventory'] },
  rain: { isolation: 'global', compatibility: ['weather'] },
  rayTrace: { isolation: 'global', compatibility: [] },
  scoreboard: { isolation: 'global', compatibility: ['scoreboard'] },
  sign: { isolation: 'global', compatibility: ['blocks:sign'] },
  sound: { isolation: 'global', compatibility: ['sound', 'blocks:note_block'] },
  spawnEvent: { isolation: 'global', compatibility: ['spawn'] },
  team: { isolation: 'global', compatibility: ['team', 'scoreboard'] },
  time: { isolation: 'global', compatibility: ['time'] },
  title: { isolation: 'global', compatibility: ['title'] },
  trade: { isolation: 'global', compatibility: ['entities', 'blocks:command_block', 'inventory'] },
  useChests: { isolation: 'workspace', compatibility: [], workspaceRadius: 10 }
}
